"""Initial tables

Revision ID: 895e5106e04d
Revises: 
Create Date: 2025-05-29 22:12:43.530473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895e5106e04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
